### ISSUE TITLE
Keep an eye on React's support for <style> tags

### ISSUE THREAD

**Issue by RickWong** [RickWong/react-inline-css#2]
https://github.com/facebook/react/issues/3496#issuecomment-85495163

**Comment by RickWong** [comment]
Seems that `<style scoped />` is now supported by React.

**Comment by RickWong** [comment]
Browser support, not so much. http://caniuse.com/#feat=style-scoped

**Comment by kevinSuttle** [comment]
> Seems that `<style scoped />` is now supported by React.

Link?
