### ISSUE TITLE
Allow to change the root selector, which is always # + componentName

### ISSUE THREAD

**Issue by vladejs** [RickWong/react-inline-css#27]
I'm having trouble rendering HTML with this library and puppeteer.

Input:
```
& .app-page { blablabla }
```

Output:
```
#InlineCss-0 .app-page { blablabla } 
```
I need the output to be:
```
.anything-0 .app-page { ... }
```

Because puppeteer errors when it encounters the `#` character.

**Comment by RickWong** [comment]
The output is valid CSS.

**Comment by vladejs** [comment]
I haven't said that the library throws invalid CSS.

I need the flexibility of optin out of using the # characte (which selects and element by ID), and need to find it using a class instead.

**Comment by RickWong** [comment]
Why does puppeteer error?

**Comment by RickWong** [comment]
Anyway, my advice is to copy [the source file](https://github.com/RickWong/react-inline-css/blob/master/src/react-inline-css.js) to your project directly, and edit it there.

Good luck!
