### ISSUE TITLE
Integrate Autoprefixer

### ISSUE THREAD

**Issue by erikras** [RickWong/react-inline-css#3]
Any chance of running the CSS through [autoprefixer](https://github.com/postcss/autoprefixer) before it's output into the DOM? That would be awesome!

From what I can tell, it's only async.

**Comment by RickWong** [comment]
Would that mean that autoprefixer has to be included in the client-side final build? Not sure if that's gonna be performant.

**Comment by erikras** [comment]
Right... Hmm...

Could the css be `require()`d at build time through a webpack loader? It would mean that you could no longer configure it based on runtime state, but I suspect most styling is static. Oh well, was just a thought. Ever since I've gotten used to sass and autoprefixer, it makes me wince to consider going back to straight css.

**Comment by RickWong** [comment]
For run-time prefixing, one might look at projects like https://github.com/LeaVerou/prefixfree
