### ISSUE TITLE
Comma-separated rules aren't namespaced correctly

### ISSUE THREAD

**Issue by RickWong** [RickWong/react-inline-css#7]
https://github.com/RickWong/react-inline-css/issues/6#issuecomment-131661319

Not sure yet whether bug is a regression or has always been there.

**Comment by sampurcell93** [comment]
I haven't issued a PR because I don't have time at the moment to write a good fix, but I do have a working 
```
return matched.replace(/&/g, "#" + namespace);
```

Need to construct a custom RegExp object in order to use componentName instead of hardcoded &.
